APMSPII-403 - added files for status endpoint
NHSDigital/api-management-service-template pull request #13
Opened 2020-11-19 11:43 UTC by paulwalkington

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2020-11-19 14:11 UTC, Sourceless requested changes

2020-11-19 14:11 UTC, Sourceless commented on proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml
> +            <Name>pds.error.code</Name>
This is probably too PDS specific for this repo

2020-11-19 14:11 UTC, Sourceless commented on proxies/live/apiproxy/policies/ServiceCallout.CallSpineHealthcheck.xml
> +    <DisplayName>ServiceCallout.CallSpineHealthcheck</DisplayName>
Would be better to make this more generic - it won't always be a spine healthcheck

2020-11-19 14:11 UTC, Sourceless commented on proxies/live/apiproxy/resources/jsc/SetStatusResponse.js
> +var spine_response_code = context.getVariable('spineHealthcheckResponse.status.code');
This could also do with being much more generic, spine won't necessarily be involved

2020-11-19 14:55 UTC, paulwalkington commented on proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml
> +            <Name>pds.error.code</Name>
shall i just make this a simple generic fault?

2020-11-19 14:55 UTC, paulwalkington commented on proxies/live/apiproxy/policies/ServiceCallout.CallSpineHealthcheck.xml
> +    <DisplayName>ServiceCallout.CallSpineHealthcheck</DisplayName>
I can change the name of this

2020-11-19 14:55 UTC, paulwalkington commented on proxies/live/apiproxy/resources/jsc/SetStatusResponse.js
> +var spine_response_code = context.getVariable('spineHealthcheckResponse.status.code');
i'll change the name of this

2020-11-19 15:43 UTC, paulwalkington commented on proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml
> +            <Name>pds.error.code</Name>
removed pds varaibles

2020-11-19 15:51 UTC, Sourceless approved these changes
LGTM

2020-11-26 17:15 UTC, alexhawdon requested changes

2020-11-26 17:22 UTC, alexhawdon approved these changes

2020-11-30 09:35 UTC, merged